# Generated by Django 2.2.1 on 2019-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.FloatField(default=0),
        ),
    ]
