# Generated by Django 2.2.1 on 2019-06-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20190620_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='minutes',
            field=models.FloatField(default=0),
        ),
    ]
