# Generated by Django 2.2.1 on 2019-06-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
