# Generated by Django 2.2.1 on 2019-06-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_player_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
