# Generated by Django 2.2.1 on 2019-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20190622_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
